name: CI/CD Pipeline for user-api

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Setup SSH Key
      - name: Setup SSH Key
        env:
          SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "$SSH_KEY" | base64 --decode > s.pem
          chmod 400 s.pem

      # Step 2: Connect to EC2 and Pull Latest Code
      - name: Pull Latest Code from Git
        env:
          EC2_USER: ${{ secrets.DEPLOY_USER }}
          EC2_IP: ${{ secrets.DEPLOY_SERVER }}
        run: |
          ssh -i s.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP'
            cd /home/ubuntu/test
            git pull origin master
          '

      # Step 3: Build Go Application
      - name: Testing and Building Go Application
        env:
          EC2_USER: ${{ secrets.DEPLOY_USER }}
          EC2_IP: ${{ secrets.DEPLOY_SERVER }}
        run: |
          ssh -i s.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP
            # Update system packages
            sudo apt update
            sudo apt install -y golang-go

            # Verify Go installation
            go version

            # Navigate to the project directory and build the app
            cd /home/ubuntu/test
            go mod tidy
            go test ./... -v
            go build -o user-api ./cmd/main.go
          

      # Step 4: Restart Application Service
      - name: Restart Application Service
        env:
          EC2_USER: ${{ secrets.DEPLOY_USER }}
          EC2_IP: ${{ secrets.DEPLOY_SERVER }}
        run: |
          ssh -i s.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP
            sudo systemctl restart thefurnishstore.service
          

      # Step 5: Cleanup SSH Key
      - name: Cleanup
        run: |
          rm -f s.pem
